### ISSUE TITLE
[ENH] Instructions on how to build maven artifacts

### ISSUE THREAD

**Issue by DragonAxe** [jcefmaven/jcefmaven#115]
**Is your feature request related to a problem? Please describe.**
How do I build maven artifacts locally on my machine, or using github actions?

**Describe the solution you'd like**
I would like to see documentation added to the README explaining how to build the jcefmaven project.

**Describe alternatives you've considered**
Looking at `workflows/maven-release.yml`, I see two required parameters to run the github action.
1. 'Build meta to use as source'
2. 'Maven version to use'

The first appears to be a URL to a `build_meta.json` file with contents [following this format](https://github.com/jcefmaven/jcefmaven/blob/master/templates/api/build_meta.json). Where could I find a populated file and how could I create/use a custom file for a custom build?
The second parameter I think could be the latest version of maven, e.g. "3.9.9".

The two parameters above are also required for most of the build scripts, so I am at a loss as how to build locally as well.

I've also looked at the `jcefbuild` repository, but that doesn't seem to produce maven artifacts that I could use with Maven/Gradle.

**Additional context**
Background: I am trying to build a customized version of the `java-cef` repository for use in a Gradle project.

**Comment by FriwiDev** [comment]
Hey there and sorry for the late reply. The build of maven artifacts consists of two steps: First jcefbuild builds all the artifacts following the originally intended jcef folder structure. Alongside those files, a build meta file will be generated. Then, jcefmaven will build the maven artifacts given the download instructions provided by the build meta file from the other repository. It will download the jcefbuild artifacts, unpack them, move stuff around a bit, then repack and push the artifact (along with some building). Feel free to ask any further questions below here, but I will close this for now as it is not really an issue :)
