### ISSUE TITLE
[BUG] StackOverflowException when OSR browser gains Focus

### ISSUE THREAD

**Issue by nprice-flextrade** [jcefmaven/jcefmaven#117]
**Describe the bug**
While running a JCEF-based application, I noticed some unexpected messages being written to the STDERR stream (`System.err`)

These messages simply read `Exception in thread "AWT-EventQueue-0"`

After a significant amount of effort, I tracked these down to an unreported `StackOverflowError`, being triggered by `CefClient.onGotFocus`

**To Reproduce**
1. Update the dependency in JCEF Sample App to `127.3.1`
2. Update `useOsr` to `true` in the `main` method of the JCEF Sample App
3. Run the app as normal (ensuring the necessary `--add-exports` parameters are included for Java 9+)
4. Observe the `System.err` log output contains multiple instances of `Exception in thread "AWT-EventQueue-0"`

**Expected behavior**
We shouldn't see unexpected errors...

**Environment (please complete the following information):**
 - OS: Windows
 - Architecture: amd64
 - Version: 127.3.1

**Additional context**
Putting a breakpoint in `CefClient.onGotFocus` reveals that this method is triggered repeatedly, with the following stack:
```
onGotFocus:461, CefClient (org.cef) [39]
N_SetFocus:-1, CefBrowser_N (org.cef.browser)
setFocus:502, CefBrowser_N (org.cef.browser)
onGotFocus:461, CefClient (org.cef) [38]
...
```

**Source code**
Looking at the implementation of `CefBrowser.onGotFocus`, we see this:
```
    @Override
    public void onGotFocus(CefBrowser browser) {
        if (browser == null) return;

        focusedBrowser_ = browser;
        browser.setFocus(true);
        if (focusHandler_ != null) focusHandler_.onGotFocus(browser);
    }
```
My feeling is that the call to `browser.setFocus(true)` is both unnecessary and problematic...

**Comment by nprice-flextrade** [comment]
My apologies... I've just realised that `CefClient` is not part of this project; rather, it's part of the JCEP API code... I'll raise a new Issue there.

**Comment by FriwiDev** [comment]
You are right, thank you anyways for the report! It indeed seems like this cant be intended :)

**Comment by Rocketeer007** [comment]
For reference, the issue raised on the JCEF project is here: https://github.com/chromiumembedded/java-cef/issues/489
