### ISSUE TITLE
[ENH] Can we use a more predicatable versioninig scheme?

### ISSUE THREAD

**Issue by smac89** [jcefmaven/jcefmaven#17]
**Is your feature request related to a problem? Please describe.**
The current versioning scheme used for the maven project is a bit unwieldy and can be difficult to comprehend for anyone not familiar with the [versioning scheme](https://bitbucket.org/chromiumembedded/cef/issues/2596/improve-cef-version-number-format#comment-50679036) used by the cef team.

**Describe the solution you'd like**
I believe a more predictable versioning scheme could be very useful for developers looking to make use of this project. Something that follows the semantic versioning format would be more predictable to developers.

i.e. `95.7.14` vs  `v1.0.0+jcef-544024e+cef-95.7.14+g9f72f35+chromium-95.0.4638.69`

**Describe alternatives you've considered**
An alternative may be to directly use the chromium version, which in the above case would be:
 `95.0.4638.69` vs `v1.0.0+jcef-544024e+cef-95.7.14+g9f72f35+chromium-95.0.4638.69`

I mean it's still better than the current format, but now we are tracking the chromium version rather than the cef version.

**Additional context**
None

**Comment by FriwiDev** [comment]
@smac89 Thank you for this suggestion. When it comes to versioning I believe that it is useful to depict the assembled components in the version name to offer transparency to developers. This helps searching issues on the web and if they already have been resolved for a certain version. Apart from that, the scheme with the `+` separated components comes from the internal building process of this repository. So I would like to keep that.

What the current versioning scheme lacks however (apart from being long due to design), is order. For this I would suggest a change to the versioning of the maven module.

The current scheme is:
`v{major}.{minor}.0+jcef-{jcef_commit}+cef-{cef_version}`

I would suggest:
`v{major}.{minor}.{build_number}+jcef-{jcef_commit}+cef-{cef_version}`

This would establish order and also track the GitHub release tags of jcefmaven (they already use semantic versioning).

Does that sound good to you? I will add a commit and pause the build bot so I do not build before this is resolved :)

**Comment by smac89** [comment]
@FriwiDev I think this is adding further complexity.

The CEF guys already use a [versioning scheme](https://bitbucket.org/chromiumembedded/cef/issues/2596/improve-cef-version-number-format#comment-50679036) that is designed to track chromium builds. and it is described [here](https://bitbucket.org/chromiumembedded/cef/issues/2596/improve-cef-version-number-format#comment-50679036).

Prepending another versioning scheme over the already existing one just seems redundant to me. I know this was the practice previously in jcefbuild, but that's because we were tracking builds at the time. Considering that this repo will supply maven artifacts for consumption by developers and their tools, I believe a more simplified versioning (preferably one that follows semantic versioning) makes more sense.

For example, using this [semver validator](https://jubianchi.github.io/semver-check/#/version/v1.0.0%2Bjcef-544024e%2Bcef-95.7.14%2Bg9f72f35%2Bchromium-95.0.4638.69) tool to check the current versioning scheme, the tool is unable to predict the next versions.

**Comment by FriwiDev** [comment]
@smac89 The problem I see is that using semantic versioning from CEF will lead to not being able to publish multiple jcef releases for one cef version. As far as I know semantic versioning also only consists of 3 numbers, if I'm not mistaken. So that could produce difficulties too.

**Comment by smac89** [comment]
@FriwiDev Hmm can you give an example of multiple jcef releases for one cef version

**Comment by FriwiDev** [comment]
@smac89 I mean every version that is not a direct bump of the CEF version, for example bugfixes like https://bitbucket.org/chromiumembedded/java-cef/commits/62432af095e85bae5fa73eaab7b0efe62197fc6a

Then there are more than one build of jcef for one build of cef. How would you suggest indicating that in semantic versioning?

**Comment by smac89** [comment]
@FriwiDev I didn't know this was tracking individual commits as well. Well in that case, how about something like `95.7.14+g9f72f35` for tracking commits, and `95.7.14` for tracking release versions

**Comment by FriwiDev** [comment]
@smac89 So a release version would be the commit bumping the cef version?

**Comment by FriwiDev** [comment]
@smac89 If we need to count to determine a release version, we could also use prerelease numbers. So like the two current versions would become:

`v1.0.0+jcef-ae6912a+cef-95.7.14+g9f72f35+chromium-95.0.4638.69` -> `95.7.14`
`v1.0.0+jcef-544024e+cef-95.7.14+g9f72f35+chromium-95.0.4638.69` -> `95.7.14.1` (newer version)

**Comment by smac89** [comment]
I like that suggestion. So the `1` at the end will just be bumped up with each newer commit for that cef release?

**Comment by FriwiDev** [comment]
@smac89 I just updated the repo (still need to update the bot) to accept the maven version as build input from the bot. As I have it implemented right now, only the "jcefmaven" artifact will use semantic versioning. The jcef-api and jcef-natives-* artifacts will continue to use the bigger version format to indicate contents and prevent a lot of changes that would be necessary to the build process (would need changing of download behaviour etc.).

**Comment by FriwiDev** [comment]
@smac89 I'm done updating the bot. Do you agree that it is enough to use semver for the main `jcefmaven` artifacts only and keep using the longer format for api and natives? If so, I can start updating :)

**Comment by smac89** [comment]
@FriwiDev  definitely. This is a nice improvement. Thanks

**Comment by FriwiDev** [comment]
@smac89 Alright. I'll deploy artifacts with the new versioning scheme tomorrow. I will just need to add broken build detection to the bot so I do not deploy any broken builds now or in the future. The newest jcef version unfortunately implements a build error on linux (due to a wrong script path).

**Comment by FriwiDev** [comment]
@smac89 I tested everything and the bot is now resuming to trigger builds on all 3 repositories. Artifacts should all be available in the next hours :)
