### ISSUE TITLE
maven repo

### ISSUE THREAD

**Issue by razorTwo** [jcefmaven/jcefmaven#3]
Is it possible to do this repo directly into maven?
this where the best and easiest way
because i found a repo of you from Tollo4 or Tello4

thx

**Comment by FriwiDev** [comment]
I host it myself to be able to swap out artifacts if there are any failed builds. Chances are, that by deploying it to the main repository, a lot of corrupted builds are uploaded. Is there any particular disadvantage in hosting the build myself, beside redundancy?

**Comment by razorTwo** [comment]
the problem is, i work in a firm, there only take the maven repository self, i cant use an extra repo in my pom or settings, thats why i ask?

**Comment by FriwiDev** [comment]
Ok, I understand your issue now. I plan on doing some changes in february and could apply to publish to the central repository after completing the changes (more stable builds and less external dependencies). I don't know how successful that would be however, as I am probably not allowed to publish jcef on the central repository without written permission by the authors.

**Comment by razorTwo** [comment]
thx, i will tell you the next time, is that impossible, because i open an task to the special maven group to import your repo, i hope there do this, and i hope you will be actually with this packages, because we use the jcef package inside a project :-)
