### ISSUE TITLE
Completely blank screen

### ISSUE THREAD

**Issue by siauderman** [jcefmaven/jcefmaven#30]
I just tried to upgrade from 84.3.8+gc8a556f+chromium-84.0.4147.105-build-17 to the latest version and I got a complete blank screen. This is the case on both MacOS and Windows. It was working fine on Windows perfectly previously.

However, 84.3.8+gc8a556f+chromium-84.0.4147.105-build-17 was not working on MacOS. I tried to add the jcef-bundle-maven-plugin, to no avail (my project uses gradle).

Hope you will be able to help me out!

**Comment by FriwiDev** [comment]
@siauderman The new version changed the build process significantly. Make sure to remove the bundle plugin from your build process - it does not work anymore and also is not required anymore. You will also want to remove the friwi.me repository from your pom or settings (you can keep it, but its not useful anymore). Make sure to adapt your code to the new API, if you have not done that already. If your code still doesn't work, then make sure you debug against the sample app. Try the sample app (other repo in this org) on your target distributions. If it doesn't work, please report a failure on this repo (new issue -> test report). If it works, then its not our fault and you should debug your code (what does your code different compared to the sample app).

In new JCEF versions it is required to add a message router to the cef client to not get a blank screen. Have you added a message router to your cef client like this?:
```java
CefMessageRouter msgRouter = CefMessageRouter.create();
client.addMessageRouter(msgRouter);
```

**Comment by siauderman** [comment]
Managed to get it working on Windows, thanks!

It's not working on Mac, but I think it's a LWJGL3 and AWT conflict issue there.

**Comment by FriwiDev** [comment]
@siauderman Have you tried to run the [sample app](https://github.com/jcefmaven/jcefsampleapp/releases/tag/95.7.14.3) on your Mac to find out if its an issue with the library itself? If not, it would help a great bit to have a test result from your Mac :)

**Comment by FriwiDev** [comment]
Thank you for the feedback :)

**Comment by siauderman** [comment]
FYI, I managed to get my app working! https://github.com/libgdx/libgdx/pull/6772#issuecomment-1016806176

**Comment by siauderman** [comment]
Hi is it possible for you to help me with this?

When I run the jar on Mac it works. However, when I jpackage it and I run the installed app, I get this error and JCEF cannot launch:

```
Jan 26, 2022 10:17:35 AM me.friwi.jcefmaven.impl.step.extract.TarGzExtractor extractTarGZ
SEVERE: Unable to create directory '%s', during extraction of archive contents.
```

Any idea of what's causing this or what might be a possible workaround?

**Comment by FriwiDev** [comment]
Are you sure that you are not passing %s as install directory to jcefmaven?

**Comment by siauderman** [comment]
> Are you sure that you are not passing %s as install directory to jcefmaven?

Definitely not, I'm not passing anything in. When I run the jar using java -jar, it extracts to jcef-bundle in the same folder as expected. The problem only occurs in DMG / PKG.

**Comment by FriwiDev** [comment]
Then try to debug where the %s comes from. Maybe your packaging tool sets an invalid working directory of some sort. I sadly can not assist that much with this error, as I don't know jpackage.

**Comment by siauderman** [comment]
> Then try to debug where the %s comes from. Maybe your packaging tool sets an invalid working directory of some sort. I sadly can not assist that much with this error, as I don't know jpackage. You could try specifying a valid directory and thus force jcefmaven to use a specific path.

Thanks for your advice, problem solved!

In case anybody else asks you about MacOS, this is what I did:

Upgraded to version 95.7.14.4 (due to xattr issue)
Did this before calling builder.build():
```
CefAppBuilder builder=new CefAppBuilder();
if(System.getProperty("os.name","").toLowerCase().startsWith("mac"))builder.setInstallDir(new File(System.getProperty("java.io.tmpdir")+"/tuxfight/jcef-bundle"));
```
Used this command to call jpackage:
```
jpackage -i tuxfight -t dmg --app-version 1.0.4 --copyright "© 2022 Custom Automated Systems ® Pte Ltd / Wilson Foo Yu Kang. All rights reserved." --description "Battle it out with other Tuxes! Fight to dominate Antarctica and be the supreme penguin. You can choose to be Ice Tux, Fish Tux, Tech Tux and Fire Tux. Each of them has different abilities and powers. Control the players using a keyboard or the on-screen controls. There is even a split screen mode so you can play with another person at the same time, using on-screen controls at opposite ends of your touchscreen!" --vendor "Custom Automated Systems ® Pte Ltd" --icon Bitbucket/TuxFight/core/src/main/images/tuxfight.icns --main-class com.customautosys.tuxfight.desktop.Lwjgl3Launcher --main-jar TuxFight-1.0.4.jar --java-options "--add-exports=java.desktop/sun.awt=ALL-UNNAMED --add-exports=java.desktop/sun.lwawt=ALL-UNNAMED --add-exports=java.desktop/sun.lwawt.macosx=ALL-UNNAMED" -n TuxFight --mac-package-identifier TuxFight --mac-package-name TuxFight
```
The only thing in the tuxfight folder is TuxFight-1.0.4.jar. The important thing to fix the bug is --java-options "--add-exports=java.desktop/sun.awt=ALL-UNNAMED --add-exports=java.desktop/sun.lwawt=ALL-UNNAMED --add-exports=java.desktop/sun.lwawt.macosx=ALL-UNNAMED".

Hope this will help anyone facing MacOS problems with jpackage in the future!

**Comment by FriwiDev** [comment]
You can use `EnumPlatform.getCurrentPlatform().getOs().isMacosx()` too to check if you are running on macosx ;)

**Comment by siauderman** [comment]
> You can use `EnumPlatform.getCurrentPlatform().getOs().isMacosx()` too to check if you are running on macosx ;)

Dear @FriwiDev,

No obligation to help, just asking a question.

I built an MSI with jpackage which works perfectly. However, after I converted the MSI to MSIX and uploaded it to the Microsoft Store, I am getting an error that the app is unable to launch the JVM when launching JCEF.

![bildo](https://user-images.githubusercontent.com/14951259/153740559-7000824c-5f58-489a-b132-94c97ba4cb3a.png)

Just wondering if you can help because this error is really strange. When I launch the corresponding .exe in the folder installed by Microsoft Store in cmd, there is nothing displayed in the console - no Exception stack trace or anything. And of course, if the problem was the bundled JVM, the app should not have been able to launch in the first place (and there's no reason why the MSI works but the MSIX doesn't).

Thanks!

**Comment by FriwiDev** [comment]
I sadly dont have any experience with Microsoft App Bundles, but I'd try to generate an exe file using jpackage and then using [makeapp.exe](https://docs.microsoft.com/de-de/windows/msix/package/create-app-package-with-makeappx-tool) to package the exe file directly to an appx/msix file for deployment. Im not sure if the environment is configured properly when converting a file with predefined environment to another file with environment (msi to msix) compared to when converting a file without integrated environment (exe) to msix. Feel free to keep me updated here on any progress you make - it might also be relevant for others :)

**Comment by siauderman** [comment]
> I sadly dont have any experience with Microsoft App Bundles, but I'd try to generate an exe file using jpackage and then using [makeapp.exe](https://docs.microsoft.com/de-de/windows/msix/package/create-app-package-with-makeappx-tool) to package the exe file directly to an appx/msix file for deployment. Im not sure if the environment is configured properly when converting a file with predefined environment to another file with environment (msi to msix) compared to when converting a file without integrated environment (exe) to msix. Feel free to keep me updated here on any progress you make - it might also be relevant for others :)

Problem solved!

The problems were that with the MSIX converter tool:
The jcef-bundle was not being extracted
The current working directory was not changed to the installation folder of the app

Therefore I solved it by:
Installing using my NSIS EXE installer
Running the app once to cause it to extract the jcef-bundle
Using Package Support Framework to change the current working directory to the app installation directory when running: https://www.advancedinstaller.com/how-to-fix-msix-limitations-with-psf.html / https://github.com/microsoft/MSIX-PackageSupportFramework/releases
Using makeappx manually (```"\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\makeappx.exe" pack /d TuxFight /p TuxFight.appx```) with my own appxmanifest.xml instead of using the MSIX converter tool (this has the added benefit of fixing the screwed up icons which were generated by the MSIX converter tool).

Here's my appxmanifest.xml:

```
<?xml version="1.0" encoding="utf-8"?>
<Package xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10"
    xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10"
    xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities">
    <Identity Name="CustomAutomatedSystemsPte.TuxFight" Version="1.0.4.0" Publisher="CN=CF94B87A-DACD-49DF-B523-D6CA466FC59D" ProcessorArchitecture="x64" />
    <Properties>
        <DisplayName>TuxFight</DisplayName>
        <PublisherDisplayName>Custom Automated Systems Pte Ltd</PublisherDisplayName>
        <Description>Battle it out with other Tuxes! Fight to dominate Antarctica and be the supreme penguin. You can choose to be Ice Tux, Fish Tux, Tech Tux and Fire Tux. Each of them has different abilities and powers. Control the players using a keyboard or the on-screen controls. There is even a split screen mode so you can play with another person at the same time, using on-screen controls at opposite ends of your touchscreen if you don't have a keyboard!</Description>
        <Logo>logos\StoreLogo.png</Logo>
    </Properties>
    <Resources>
        <Resource Language="en-us" />
    </Resources>
    <Dependencies>
        <TargetDeviceFamily Name="Windows.Desktop" MinVersion="10.0.14316.0" MaxVersionTested="10.0.17763.0" />
    </Dependencies>
    <Capabilities>
        <rescap:Capability Name="runFullTrust"/>
    </Capabilities>
    <Applications>
        <Application Id="CustomAutomatedSystemsPte.TuxFight" Executable="TuxFight.exe" EntryPoint="Windows.FullTrustApplication">
            <uap:VisualElements DisplayName="TuxFight" Description="Battle it out with other Tuxes! Fight to dominate Antarctica and be the supreme penguin. You can choose to be Ice Tux, Fish Tux, Tech Tux and Fire Tux. Each of them has different abilities and powers. Control the players using a keyboard or the on-screen controls. There is even a split screen mode so you can play with another person at the same time, using on-screen controls at opposite ends of your touchscreen if you don't have a keyboard!" Square150x150Logo="logos\Square150x150Logo.png" Square44x44Logo="logos\Square44x44Logo.png" BackgroundColor="#74e7e7">
                <uap:SplashScreen BackgroundColor="#74e7e7" Image="logos\SplashScreen.png"/>
                <uap:DefaultTile Wide310x150Logo="logos\Wide310x150Logo.png" Square310x310Logo="logos\LargeTile.png" Square71x71Logo="logos\SmallTile.png" ShortName="TuxFight">
                    <uap:ShowNameOnTiles>
                        <uap:ShowOn Tile="square150x150Logo"/>
                        <uap:ShowOn Tile="wide310x150Logo"/>
                        <uap:ShowOn Tile="square310x310Logo"/>
                    </uap:ShowNameOnTiles>
                </uap:DefaultTile>
            </uap:VisualElements>
        </Application>
    </Applications>
</Package>
```

Here's my config.json for PSF:
```
{
    "applications": [
        {
            "id": "CustomAutomatedSystemsPte.TuxFight",
            "executable": "TuxFight.exe",
            "arguments": "/k cd %MsixPackageRoot%"
        }
	]
}
```
