### ISSUE TITLE
[BUG] Running on MacOSX 10.15+ requires signing and notarization of bundled binaries

### ISSUE THREAD

**Issue by slajar** [jcefmaven/jcefmaven#36]
**Describe the bug**
The sample does start and crashes right away.

**To Reproduce**
1. Go to https://github.com/jcefmaven/jcefsampleapp
2. Ccheck it out
3. compile against latest versions from 7th janurary 2022

**Expected behavior**
Startup the sample

**Screenshots**
initialize on Thread[AWT-EventQueue-0,6,main] with library path /Users/matthias/dev/temp/jcefsampleapp/jcef-bundle
[0126/165829.728683:ERROR:gpu_process_host.cc(973)] GPU process launch failed: error_code=1003
[0126/165829.729137:WARNING:gpu_process_host.cc(1292)] The GPU process has crashed 1 time(s)
[0126/165829.732963:ERROR:gpu_process_host.cc(973)] GPU process launch failed: error_code=1003
[0126/165829.733022:WARNING:gpu_process_host.cc(1292)] The GPU process has crashed 2 time(s)
[0126/165829.736402:ERROR:gpu_process_host.cc(973)] GPU process launch failed: error_code=1003
[0126/165829.736468:WARNING:gpu_process_host.cc(1292)] The GPU process has crashed 3 time(s)
[0126/165829.773849:ERROR:gpu_process_host.cc(973)] GPU process launch failed: error_code=1003
[0126/165829.773923:WARNING:gpu_process_host.cc(1292)] The GPU process has crashed 4 time(s)
[0126/165829.777640:ERROR:gpu_process_host.cc(973)] GPU process launch failed: error_code=1003
[0126/165829.777722:WARNING:gpu_process_host.cc(1292)] The GPU process has crashed 5 time(s)
[0126/165829.781035:ERROR:gpu_process_host.cc(973)] GPU process launch failed: error_code=1003
[0126/165829.781093:WARNING:gpu_process_host.cc(1292)] The GPU process has crashed 6 time(s)
[0126/165829.810352:ERROR:gpu_process_host.cc(973)] GPU process launch failed: error_code=1003
[0126/165829.810412:WARNING:gpu_process_host.cc(1292)] The GPU process has crashed 7 time(s)
[0126/165829.813863:ERROR:gpu_process_host.cc(973)] GPU process launch failed: error_code=1003
[0126/165829.813943:WARNING:gpu_process_host.cc(1292)] The GPU process has crashed 8 time(s)
[0126/165829.817894:ERROR:gpu_process_host.cc(973)] GPU process launch failed: error_code=1003
[0126/165829.817971:WARNING:gpu_process_host.cc(1292)] The GPU process has crashed 9 time(s)
[0126/165829.818002:FATAL:gpu_data_manager_impl_private.cc(417)] GPU process isn't usable. Goodbye.

**Environment (please complete the following information):**
 - OS: MacOSX 11.6.1 till 12.1 tested
 - Architecture: both x64 
 - Version 95.7.14.4

**Additional context**
-

**Source code**
https://github.com/jcefmaven/jcefsampleapp

**Comment by tobium** [comment]
I have the same crash on Mac 12.1 using JDK 8 and 11

**Comment by FriwiDev** [comment]
This is most likely a bug in JCEF/CEF itself, not jcefmaven. Please consider reporting it to the main JCEF project on bitbucket. I'll leave this open to track the progress of the issue. Please feel free to post a link to your submitted issue :)

**Comment by slajar** [comment]
Well, I have a self build jcef from current sources and this works, but I don't like to use manual build packages so jcefmaven comes into place.

**Comment by slajar** [comment]
Who is reponsible for those binary native packages in here?

**Comment by FriwiDev** [comment]
Me, on jcefmaven/jcefbuild repository. Can you test if the packages there work for you?

**Comment by FriwiDev** [comment]
I mean the prebuilt downloadable packages. It does compile through on github action runners though. Most likely in your case there is already a build error further up in the log and it cannot compile jcef.

**Comment by slajar** [comment]
@FriwiDev I am obviously confused :) Can you please provide me a link to what you mean?

**Comment by FriwiDev** [comment]
https://github.com/jcefmaven/jcefbuild/releases/

**Comment by FriwiDev** [comment]
If it is the helper apps that need to be signed (by default, you do not need to use an own app), I might be able to provide a signature for them as well. Up to now I have not worked with apples signature system. If you can provide some steps to perform to make the helpers run on MacOS 12+, then I would be glad to provide a general fix for it.

**Comment by FriwiDev** [comment]
Most likely all helper apps would need to be signed like [this](https://github.com/devbotsxyz/example-macos-rings/blob/master/.github/workflows/release.yml) by [jcefbuild](https://github.com/jcefmaven/jcefbuild) for this issue to be resolved. I will consider implementing this in the future - I would need an apple developer ID for this though and there could be potential issues with me signing code I'm not in control of. Maybe there is also other solutions to keep gatekeeper at bay. In my v10 macos it seems to be enough to unquarantine the extracted files with a console command. Maybe this could work on v12 too with some adaptions. Feel free to test how to circumvent the problem in another way. Providing signatures would be the last resort on my side, as I also do not own an apple developer ID yet to sign stuff.

**Comment by FriwiDev** [comment]
@slajar Can you please try on your Mac to right click all of the helper .apps (individually) and open them, by selecting open in the next dialog, so that the apps are whitelisted in gatekeeper (maybe you have to confirm in system settings). After whitelisting all 4 helper apps, try running the sample app again. If this works, signing should definitly be the solution and I'd be willing to do that to fix functionality for OSX 11+ :)

**Comment by FriwiDev** [comment]
This is also closely related to CEF issue (https://bitbucket.org/chromiumembedded/cef/issues/2744/macos-document-code-signing-process-with)[2744].
I guess our issues could be resolved by implementing the solution presented (https://magpcss.org/ceforum/viewtopic.php?f=6&t=16481&start=10#p43161)[here] in the 19th post. By signing and then notarizing all required files (maybe only the helper apps, or also the dylib files), this issue on MacOS 10.15+ should probably be resolved.

**Comment by FriwiDev** [comment]
I plan to work on this in the next two weeks, but of course can not promise success yet.

**Comment by FriwiDev** [comment]
Quick update: I started introducing code signing to jcefbuild. See this commit: https://github.com/jcefmaven/jcefbuild/commit/d9e5fe14eaac7bd48500bc9fcd61aee8be463fdc

**Comment by FriwiDev** [comment]
@slajar @tobium Starting from version 95.7.14.8, all libraries and helper bundles are now code signed with an MacOS Distribution Certificate. Make sure to report if this fixes your problem! :)

[The new version should be available within the next hour.]

**Comment by FriwiDev** [comment]
> A collegue of mine just found a fix the issue :) The app must be signed, otherwise, the MacOSX seems to fail here. I am going to prepare a patch for the Readme.

@slajar Hmm, the error still seems to occur even after signing all contents and even after disabling gatekeeper. Can you tell what your collegue changed to get it working? It would help a lot, as without this being resolved the lib is impossible to use on newer macos versions :(

**Comment by slajar** [comment]
@FriwiDev since I am quite sure that we are living in the same region or even city, would it help if we arrange a small hackathon with our developers? Actually, we found a way around this for us that is working. You can contact us here: https://www.onexip.com/contact/

**Comment by FriwiDev** [comment]
@slajar It turns out I signed with the wrong certificate from apple. I now switched the certificate to the correct one and sign and notarize everything (apart from jogl and gluegen in jcefmaven). If this doesn't resolve the issue I'll gladly accept your invitation to a small hackathon to resolve this issue. We do indeed live/work in the same city ;)

**Comment by mab** [comment]
Having the same issue. With 95.7.14.9 on MacOSX 12.2.1.

**Comment by slajar** [comment]
@FriwiDev sure, just drop us a message in the contact form and we will negotiate a meeting over here :)

**Comment by bschf** [comment]
With 95.7.14.9 on OSX 11.2.3 we needed to remove the quarantine flag from the downloaded jcef-bundle folder

    sudo xattr -r -d com.apple.quarantine jcef-bundle

To overcome private api access, we use following vm flags

    --add-exports java.desktop/sun.awt=ALL-UNNAMED 
    --add-exports java.desktop/java.awt.peer=ALL-UNNAMED 
    --add-exports java.desktop/sun.lwawt.macosx=ALL-UNNAMED
    --add-exports java.desktop/sun.lwawt=ALL-UNNAMED

(found them here https://github.com/JetBrains/jcef/blob/master/build.xml)

**Comment by FriwiDev** [comment]
The code signing and notarization is now working correctly and starting from version 95.7.14.10, builds run perfectly on newer macosx versions. Thanks to @slajar and his team to discover the fix and for the kind invitation :)

**Comment by slajar** [comment]
you are always welcome.

**Comment by FriwiDev** [comment]
I made a mistake with the quarantine flag which is now solved in 95.7.14.11. Now it should finally run :partying_face:
