### ISSUE TITLE
Empty jar files

### ISSUE THREAD

**Issue by rutenkolk** [jcefmaven/jcefmaven#4]
I just wanted to try out the fat-jars, as this would be the most comfortable way to develop and deploy any app written with jcef and I noticed that the jars are mostly empty. Did anything go wrong here?

For example: 
https://friwi.me/jcef/maven/org/cef/jcef-main/84.3.8%2Bgc8a556f%2Bchromium-84.0.4147.105-build-17/jcef-main-84.3.8%2Bgc8a556f%2Bchromium-84.0.4147.105-build-17.jar
contains almost next to nothing. In fact there is only one `TAG` class inside, that seems to be auto generated.

**Comment by rutenkolk** [comment]
I just noticed, that this is intentional and the transitive dependencies include all that is needed.

It's been a while since I actually used maven, sorry.

The actual error then would be a gradle incompatibility which confused me.

**Comment by FriwiDev** [comment]
I'm actually not sure that build 17 is complete. The jcefbuild did not succeed some while ago so I guess my build script failed too. Build 16 is tested to be working.
