### ISSUE TITLE
Utilizing JCEF as a layer to render UI for games on top of OpenGL/Vulkan

### ISSUE THREAD

**Issue by alothmanmoe** [jcefmaven/jcefmaven#41]
Hey there, this is more of a question/discussion rather than an issue.

I'm looking to try and implement UI's for games written in HTML/CSS/JS using CEF. Currently, I'm working with Java and OpenGL but also Vulkan coming in the near future. Looking at JCEF it seems to be built using Java's AWT framework and JFrames. Is there a nice way to still utilize this and write an OpenGL renderer for it?

**Comment by liulihaocai** [comment]
I'm working on it nowadays too, I want to make a morden GUI for my Minecraft mod. So I found there exists a JCef modify that allowed to use LWJGL to render it https://github.com/montoyo/mcef , but it's quite old, I want to use the latest one. 
Then I make a custom CefBrowserOsr by `extends CefBrowser_N implements CefRenderHandler` https://github.com/UnlegitMC/FDPClient/blob/jcef/src/main/java/org/cef/browser/CefBrowserCustom.java and now its working well.
![image](https://user-images.githubusercontent.com/65506006/153737634-b4f47ae1-9311-40d2-a67b-4ca14b4cdfe3.png)

**Comment by FriwiDev** [comment]
If you want to render on top of an lwjgl window, another option would also be to create a jframe instead, add a lwjgl canvas to it and then add jcef in an awt component on top of it. This would enable onscreen rendering on top of an opengl surface.
