### ISSUE TITLE
[BUG] Mac M1 JDK 17 - sample app fails to start

### ISSUE THREAD

**Issue by ptrthomas** [jcefmaven/jcefmaven#45]
Cloned https://github.com/jcefmaven/jcefsampleapp
Used maven version 95.7.14.11
`mvn compile exec:java -Dexec.mainClass=me.friwi.jcefsampleapp.MainFrame`

my Java version is:
```
java 17.0.1 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
```

OS:
```
System Version:	macOS 12.2.1 (21D62)
Kernel Version:	Darwin 21.3.0
Model Name:	MacBook Pro
Model Identifier:	MacBookPro18,1
Chip:	Apple M1 Pro
```

Error:
```
initialize on Thread[AWT-EventQueue-0,6,me.friwi.jcefsampleapp.MainFrame] with library path /Users/peter/dev/ycode/jcefsampleapp/jcef-bundle
[WARNING] 
java.lang.IllegalAccessError: class org.cef.browser.mac.CefBrowserWindowMac (in unnamed module @0x7a75d5e6) cannot access class sun.awt.AWTAccessor (in module java.desktop) because module java.desktop does not export sun.awt to unnamed module @0x7a75d5e6
    at org.cef.browser.mac.CefBrowserWindowMac.getWindowHandle (CefBrowserWindowMac.java:27)
    at org.cef.browser.CefBrowserWr.getWindowHandle (CefBrowserWr.java:337)
    at org.cef.browser.CefBrowserWr.access$600 (CefBrowserWr.java:49)
    at org.cef.browser.CefBrowserWr$3.addNotify (CefBrowserWr.java:232)
    at java.awt.Container.addNotify (Container.java:2804)
    at javax.swing.JComponent.addNotify (JComponent.java:4839)
    at java.awt.Container.addNotify (Container.java:2804)
    at javax.swing.JComponent.addNotify (JComponent.java:4839)
    at java.awt.Container.addNotify (Container.java:2804)
    at javax.swing.JComponent.addNotify (JComponent.java:4839)
    at javax.swing.JRootPane.addNotify (JRootPane.java:729)
    at java.awt.Container.addNotify (Container.java:2804)
    at java.awt.Window.addNotify (Window.java:791)
    at java.awt.Frame.addNotify (Frame.java:495)
    at java.awt.Window.pack (Window.java:829)
    at me.friwi.jcefsampleapp.MainFrame.<init> (MainFrame.java:173)
    at me.friwi.jcefsampleapp.MainFrame.main (MainFrame.java:197)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:833)
```

**Comment by ptrthomas** [comment]
an update. so this most certainly is the combination of Java 17 and Apple Silicon / M1

I switched to Java 11 on the same machine and it worked fine (using [Rosetta](https://support.apple.com/en-in/HT211861))
```
java 11.0.12 2021-07-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)
```

**Comment by FriwiDev** [comment]
This is not a bug by this project, but by jcef itself. Please report it on the official issue tracker. Another similar problem is this: https://bitbucket.org/chromiumembedded/java-cef/issues/396/javalangarrayindexoutofboundsexception (also jdk 17 related). I think it is questionable wether jcef can manage to create support for jdk 17+, as without internal access things will hardly work.

**Comment by ptrthomas** [comment]
@FriwiDev agreed, I will close this issue. thank you and the whole team for this project, really hope that JDK 17 will be possible in the future.

can I suggest an enhancement that you have a script or recipe to bundle a JRE or JDK along with this project, using jlink or something similar.

**Comment by FriwiDev** [comment]
This is sort of planned, but should currently be feasible using standard tools. I would leave this open for now. We can collect which internal packages need to be opened for jcef to run on jdk 17 and include it in the readme. For example in your case, you would need to add:

--add-opens java.desktop/sun.awt=ALL-UNNAMED

**Comment by ptrthomas** [comment]
@FriwiDev wow that's awesome. I was able to get it to work with the following JVM options

```
--add-opens java.desktop/sun.awt=ALL-UNNAMED --add-opens java.desktop/sun.lwawt=ALL-UNNAMED --add-opens java.desktop/sun.lwawt.macosx=ALL-UNNAMED
```

**Comment by FriwiDev** [comment]
To use jogl on jdk 17 (osr mode in jcef), one must add these arguments:

```
--add-exports java.base/java.lang=ALL-UNNAMED
--add-exports java.desktop/sun.awt=ALL-UNNAMED
--add-exports java.desktop/sun.java2d=ALL-UNNAMED
```

**Comment by FriwiDev** [comment]
I just included this info in the readme under limitations. Thanks for your report! Feel free to report additional opens if it fails under other platforms for some similar reason :)

**Comment by ptrthomas** [comment]
@FriwiDev I have a question - I was experimenting with [jpackage](https://docs.oracle.com/en/java/javase/14/jpackage/packaging-overview.html#GUID-C1027043-587D-418D-8188-EF8F44A4C06A) on JDK 17

after I created a DMG and used it to land a *.app file in `/Applications` - double clicking on the executable would start the process but nothing would be seen on screen

the good news is - if I go to the command line, and do this:

```
myjar.app/Contents/MacOS/Main
```

it works ! are you aware of what a mac executable does by default from a "UI rendering" point of view that causes this problem by any chance

**Comment by FriwiDev** [comment]
I sadly do not know too much about MacOS app bundling. Maybe your plist file contains a wrong executable path.

**Comment by ptrthomas** [comment]
@FriwiDev no worries. I'll pause my experiment for now. but this is very close, and looks so promising.

just FYI - the JetBrains team maintains something called the JetBrains Runtime (JBR) - that bundles CEF and patches the JVM to work better cross-os. just mentioning here in case this is of use for anyone in the future for research: https://plugins.jetbrains.com/docs/intellij/jcef.html

**Comment by qingbinyang** [comment]
Error:
`Caused by: java.lang.IllegalArgumentException: jogl.all.v2.4.0.rc: Invalid module name: '4' is not a Java identifier`

**Comment by FriwiDev** [comment]
I currently neither use, nor have knowledge of the java module system. I'd recommend to not use anything related to modules with jcefmaven. As always, PRs implementing this functionality or fixing this issue are welcome.

**Comment by orelinde** [comment]
> @FriwiDev I have a question - I was experimenting with [jpackage](https://docs.oracle.com/en/java/javase/14/jpackage/packaging-overview.html#GUID-C1027043-587D-418D-8188-EF8F44A4C06A) on JDK 17
> 
> after I created a DMG and used it to land a *.app file in `/Applications` - double clicking on the executable would start the process but nothing would be seen on screen
> 
> the good news is - if I go to the command line, and do this:
> 
> ```
> myjar.app/Contents/MacOS/Main
> ```
> 
> it works ! are you aware of what a mac executable does by default from a "UI rendering" point of view that causes this problem by any chance

I had the same problem the last couple of days, it turned out that the application.app was not having sufficient rights to create the jcef-bundle folder.

After I changed the download location to my users home folder (for testing):

```     
var folder = System.getProperty("user.home");
builder.setInstallDir(Path.of(folder, "jcef-bundle").toFile()); 
```

Then it started working.

**Comment by FriwiDev** [comment]
Thanks a lot for this feedback/resolution! :)

**Comment by gochev** [comment]
had to start it with this VM options
--add-opens java.desktop/sun.awt=ALL-UNNAMED --add-opens java.desktop/sun.lwawt=ALL-UNNAMED --add-opens java.desktop/sun.lwawt.macosx=ALL-UNNAMED
