### ISSUE TITLE
How to new a Panel Object on the Brower Component on mac

### ISSUE THREAD

**Issue by zhangxiaotou** [jcefmaven/jcefmaven#46]
I want to use swing components on top of browser component
Here is my test code(in MainFrame.java):
`
Panel p = new Panel(); 
p.setBackground(Color.RED); 
getContentPane().add(p); 
getContentPane().add(browser.getUIComponent()); 
p.setBounds(0,0,300,300); 
browser.getUIComponent().setBounds(0,0,1200,800);
//browser.getUIComponent().setBounds(100,100,1200,800); //mac test
`
It works on windows system as shown（OpenJDK17）
![window_test](https://user-images.githubusercontent.com/43879878/161789796-bf80b9c6-370d-4979-a9e6-4b433779fb51.png)

but doesn't work on mac（OpenJDK 17  M1）,it will always be below the browser component
![mac_test](https://user-images.githubusercontent.com/43879878/161791550-ed0fcb71-60a7-4582-ad23-675c60079c14.jpg)

Is there any good way to solve this problem, thank you very much

**Comment by FriwiDev** [comment]
On linux based systems overlaying swing components over the browser will only work in osr mode. This comes with a huge performance and battery cost however. If you wish to not draw a section, you will need to modify the jcef/cef binaries. It might be easier to use an iframe in the browser and model your swing component in html. I will close this for now, as this isnt an issue with jcefmaven, but with jcef/cef. Feel free to still reply to this so we can have a discussion :)

**Comment by zhangxiaotou** [comment]
Thank you for your reply.Interestingly, I thought of a tricky way to solve this problem: generate a JDialog as the carrier of the Swing component, and then the JDialog moves with the MainFrame.When I move the MainFrame, this JDialog works perfectly on windows, but moves very slowly on mac, do you know why.
Here is my code：
```
public class FloatContainer extends JDialog {

    private ComponentListener lastListener;
    private JFrame owner;

    public FloatContainer(JFrame owner) {
        super(owner, null, false);
        this.owner = owner;
        setLayout(new BorderLayout());
        setUndecorated(true);
        getRootPane().putClientProperty("Window.shadow", Boolean.FALSE);//remove JDialog's titlebar and border on mac
        JPanel jPanel = new JPanel();
        jPanel.setBackground(Color.RED);
        add(jPanel,BorderLayout.CENTER);
    }
    /**
     * Set the size and position of the container
     * @param width
     * @param height
     * @param left
     * @param top
     */
    public void setLocation(int width,int height,int left,int top){
        setSize(width, height);
        if (lastListener != null)
            owner.removeComponentListener(lastListener);
        lastListener = new ComponentAdapter() {
            @Override
            public void componentMoved(ComponentEvent e) {
                super.componentMoved(e);
                setLocation(e.getComponent().getX() + left, e.getComponent().getY() + top);
            }
        };
        owner.addComponentListener(lastListener);
        setLocation(owner.getX() + left, owner.getY() + top);
    }
}
```
in MainFrame.java:
```
        FloatContainer floatContainer = new FloatContainer(this);
        floatContainer.setVisible(true);
        floatContainer.setLocation(300,300,0,0);
        getContentPane().add(getBrowser().getUIComponent());
```
<img width="809" alt="JDialog-test" src="https://user-images.githubusercontent.com/43879878/162222439-9c8e1329-484c-433f-9806-6e27d5203969.png">
