### ISSUE TITLE
[BUG] Browser content is blank when sampleapp run on MacOS with JDK 1.8.0_181/JDK 1.8.0_202 

### ISSUE THREAD

**Issue by clyoudu** [jcefmaven/jcefmaven#49]
**Describe the bug**
Browser content is blank when sampleapp run on MacOS with JDK 1.8.0_181/JDK 1.8.0_202

**To Reproduce**
1. Git clone https://github.com/jcefmaven/jcefsampleapp
2. Import jcefsampleapp as maven project into IntelliJ IDEA 2019.2.3 (Ultimate Edition)
3. Set project SDK: Oracle JDK 1.8.0_181
4. Run `MainFrame` 
5. JCEF downloaded, extracted and initialized. Jframe display like this: 

<img width="800" alt="image" src="https://user-images.githubusercontent.com/9692275/168942682-59a40642-d0f1-472d-9aa3-b689e78e4b66.png">

6. Set project SDK: Oracle JDK 1.8.0_202(latest), nothing changed

**Page content can be selected/copied/clicked, although there is nothing displayed.**
**I input some words in search input area and click the search button, address and content changed but still "blank" page.**
**Copy,paste, back, forward works well.**
![jcef](https://user-images.githubusercontent.com/9692275/168946536-479b4a87-e36d-44a1-aabd-8e5c4dd66701.gif)

**Expected behavior**
Display correct web page.

**Screenshots**

**Environment (please complete the following information):**
 - OS: macosx
 - Architecture: amd64
 - Version: jcef-0aee584+cef-100.0.14+g4e5ba66+chromium-100.0.4896.75

**Additional context**
1. When I set SDK to JDK 11.0.11, every things goes well. 
2. Code in jcefsampleapp never changed so it's not a problem about `CefMessageRouter`.
3. JVM crashed somtimes: `Process finished with exit code 131 (interrupted by signal 3: SIGQUIT)`
**Source code**

**Comment by FriwiDev** [comment]
@clyoudu Thank you for your report! You should probably report this on the jcef issue tracker instead, as it does not appear to be a problem with jcefmaven. You can find the jcef project on bitbucket, a link is provided in the readme of this repository.

**Comment by FriwiDev** [comment]
Closed due to inactivity and most likely wrong issue tracker. Please report back if you think that this is in error.
