### ISSUE TITLE
[TR] Test report

### ISSUE THREAD

**Issue by DemonWitch** [jcefmaven/jcefmaven#50]
**Tag**
{mvn_version}

**OS (linux/windows/macosx)**
macosx

**Version/Flavor (e.g. Ubuntu 20.04, Windows 10, Big Sur)**
macOS 12.3.1 (12.3.1)

**Arch (amd64/i386/arm64/arm)**
arm64

**Report as working? (Y/N)**
N

**Did you test with the official sample app? (Y/N)**
Y

**Additional information**
run with error :
....
[0530/153434.107048:WARNING:gpu_process_host.cc(1292)] The GPU process has crashed 9 time(s)
[0530/153434.107075:FATAL:gpu_data_manager_impl_private.cc(417)] GPU process isn't usable. Goodbye.

**Comment by FriwiDev** [comment]
Which version were you using?

**Comment by DemonWitch** [comment]
here is my gradle settings:
plugins {
    id("org.jetbrains.intellij") version "1.5.2"
    java
}
dependencies {
    implementation("me.friwi:jcefmaven:100.0.14")
}
intellij {
    version.set("2022.1.1")
}

-----
and my idea version is also "2022.1.1"

**Comment by FriwiDev** [comment]
Are you trying to run jcefmaven from a plugin inside intellij idea? IntelliJ probably modifies a lot in its own environment which might clash with jcefmaven. Apart from that, intellij already bundles jcef alongside itself. I'd recommend to just use the jetbrains-cef included in intellij. I'm not sure if the (technically) same native library can be used twice in parallel from one java process. Feel free to comment on this issue if you have any new insights concerning this topic. I currently do not have a test environment to actively test this edge case on macosx.

**Comment by FriwiDev** [comment]
Thank you for experimenting with the configuration and finding a solution. In case this becomes a problem for more users I will consider to use this as a default configuration on macos arm64 :)
