### ISSUE TITLE
[ENH] Include maven/gradle declarations for the native artifacts in the release description.

### ISSUE THREAD

**Issue by e3ndr** [jcefmaven/jcefmaven#53]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A spoiler in the release description for the native artifacts.

**Describe alternatives you've considered**
None.

**Additional context**
It would be handy if these artifact/group ids were readily available for those of us who bundle our natives rather than have them get fetched at runtime.

**Comment by FriwiDev** [comment]
@e3ndr I included the native artifact ids in the release builder. Also the issue with input stream closing should be fixed now.
