### ISSUE TITLE
[BUG] Bundle not available for MacOSX Intel arch

### ISSUE THREAD

**Issue by pranmitt** [jcefmaven/jcefmaven#54]
Tried using latest version 104.4.23 but it does not work on Mac Intel 

Tried using OSR mode but facing following error 
"message":"GLException","stack_trace":"com.jogamp.opengl.GLException: Profiles [GL4bc, GL3bc, GL2, GLES1] not available on device null\n\tat com.jogamp.opengl.GLProfile.get(GLProfile.java:1060)\n\tat com.jogamp.opengl.GLProfile.get(GLProfile.java:1071)\n\tat com.jogamp.opengl.GLProfile.getMaxFixedFunc(GLProfile.java:824)

**Environment (please complete the following information):**
 - OS: MacOSX
 - Architecture: intel x 64
 - Version jcef-af53d63+cef-104.4.23+g46ae630+chromium-104.0.5112.102.

**Comment by FriwiDev** [comment]
Jogamp is probably not finding your graphics card. There are a bunch of results when searching your error online. Can you try to troubleshoot it a bit? Possibly there is something wrong with your OpenGL drivers or you are using a vm without access to the graphics card.

**Comment by FriwiDev** [comment]
@pranmitt Closing this due to no reply and a possible incompatibility between an internal intel gpu and jogamp. Should work fine in windowed rendering mode. If you have any new information or findings, feel free to share and I'll reopen this issue.

**Comment by pranmitt** [comment]
I disabled windowless_rendering_enabled & even tried few workarounds on google but could not make it work.
