### ISSUE TITLE
 I want to use JCEF to log in with multiple accounts on the same page. 

### ISSUE THREAD

**Issue by jh2310** [jcefmaven/jcefmaven#58]
Hello, I want to use JCEF to log in with multiple accounts on the same page. I want to ask you how to set multiple sets of cookies, that is, different clients have different cookies

**Comment by FriwiDev** [comment]
@jh2310 You can do that by using the CefCookieManager class. CefCookieManager.getGlobalManager() will give you the global instance, valid for the whole app.

Javadoc: https://friwi.me/jcef/javadoc/104.4.23/org/cef/network/CefCookieManager.html
Complete Javadoc: https://friwi.me/jcef/javadoc/104.4.23/

**Comment by jh2310** [comment]
Thank you very much for your suggestion. I checked the documents you provided, but I still can't implement a separate cookie address for a page. It seems that it always uses a cookie manager to process all pages or clients

**Comment by jh2310** [comment]
Do you have a mature dome that I can refer to? Thank you!
