### ISSUE TITLE
cookie

### ISSUE THREAD

**Issue by jh2310** [jcefmaven/jcefmaven#60]
I'm very sorry to disturb you again. I don't have your other contact information, so I can only ask you here. If I disturb you, I'm sorry
I tried the method you suggested, but I found that the website I visited sometimes put the value of the cookie in the URL or the request parameter, which must require the cookie support of the browser. Is there any other way to make a page have an independent cookie manager or an independent cookie address? I have not found an effective solution in the forum

**Comment by FriwiDev** [comment]
You can try catching the request parameters from the url yourself by subscribing to events. Would that suit your needs? I dont think there is another way.

https://friwi.me/jcef/javadoc/104.4.23/org/cef/handler/CefDisplayHandler.html#onAddressChange-org.cef.browser.CefBrowser-org.cef.browser.CefFrame-java.lang.String-

Am 06.09.2022 um 15:55 schrieb jh2310 ***@***.***>:

﻿

I'm very sorry to disturb you again. I don't have your other contact information, so I can only ask you here. If I disturb you, I'm sorry
I tried the method you suggested, but I found that the website I visited sometimes put the value of the cookie in the URL or the request parameter, which must require the cookie support of the browser. Is there any other way to make a page have an independent cookie manager or an independent cookie address? I have not found an effective solution in the forum

**Comment by jh2310** [comment]
JCEF may not be suitable for my needs. I have changed to jxbrower, but thank you anyway
