### ISSUE TITLE
[Help] Compile jcefmaven with custom fork of java-cef

### ISSUE THREAD

**Issue by ghedlund** [jcefmaven/jcefmaven#62]
First, thanks for this project - I'm currently switching my application from jxbrowser to java-cef and this project has made the transition much easier.

I have the need to compile custom versions of java-cef as there are several bug fixes which I need to apply to get my own application in production. These bugs have been reported, but of course I cannot expect those changes to propagate through the pipeline in a timeline which meets my needs.  I was wondering if you could help with instructions on how to create the necessary packages for the jcefmaven project with my custom fork of java-cef.

**Comment by FriwiDev** [comment]
Hey there - sorry for the late reply. You can simply fork the jcefbuild and jcefmaven repositories from github and run the github actions scripts using your own repository urls. But beware: You will need to supply some secrets - for example a macos developer secret if you want to deploy for macos. You can of course also remove these steps from the build as you please. The required secrets can be found in the readme of jcefbuild.

**Comment by ghedlund** [comment]
Thanks I give it a try!

**Comment by FriwiDev** [comment]
Will close this issue - feel free to reply if you have any issues with building! :)
