### ISSUE TITLE
[Help] How to implement select folder in jcef ?

### ISSUE THREAD

**Issue by humbinal** [jcefmaven/jcefmaven#65]
Hi, I am using jcef to build by app, I need to get a directory through the Select Folder dialog.
The Cefbrowser has runFileDialog method, but not found runDirectoryDialog ? 
How to implement this function ?

**Comment by FriwiDev** [comment]
Sadly, this is not possible using CEF at the moment. If you want this to be added, make sure to request it on the bitbucket repository of CEF. This here is just the maven build of the java bindings of CEF.

Alternatively you can still use JFileChooser to get what you wanted :)

**Comment by humbinal** [comment]
@FriwiDev  thank you!
