### ISSUE TITLE
Error with libjcef.so linux-kylin-v10-arm64 

### ISSUE THREAD

**Issue by tkggusraqk** [jcefmaven/jcefmaven#68]
Please follow the format strictly and do not modify the template. Please *always* test with the official sample app [here](https://github.com/jcefmaven/jcefsampleapp) (you will need to download the version using the maven artifact you want to test). You can add your own text under `Additional information`. In case the build was not working, please consider adding the console output, screenshots and steps to reproduce.

**Tag**
v108.4.13+jcef-natives-linux-arm64-jcef-c1f0745+cef-108.4.13+ga98cd4c+chromium-108.0.5359.125.jar

**OS (linux/windows/macosx)**
linux

**Version/Flavor (e.g. Ubuntu 20.04, Windows 10, Big Sur)**
kylin v10 (4.4.131-20200618.kylin.desktop.android-generic)

**Arch (amd64/i386/arm64/arm)**
arm64

**Report as working? (Y/N)**
N

**Did you test with the official sample app? (Y/N)**
Y

**Additional information**
![jcef-error](https://user-images.githubusercontent.com/5164663/209892580-b322cca9-c5d3-4471-b388-3a6489b11010.png)
![jcef-os](https://user-images.githubusercontent.com/5164663/209892584-fad7ae7e-1f4e-44ac-841e-ed4168466007.png)

**Comment by FriwiDev** [comment]
It appears you have a different set of base libraries on your system than jcef expects. You can either install glibc 2.27 on your system or compile jcef on your system using the wrappers from jcefbuild or the manual build instructions from the jcef repo. Sadly I can not help here.
