### ISSUE TITLE
Window resize Browser update delay

### ISSUE THREAD

**Issue by Link-Kou** [jcefmaven/jcefmaven#72]
**Environment**
 - OS: macosx
 - Architecture: amd64
 - Version [[tag, e.g. v1.0.0+jcef-ae6912a+cef-95.7.14+g9f72f35+chromium-95.0.4638.69]](me.friwi:jcef-natives-macosx-amd64:jcef-87476e9+cef-110.0.25+g75b1c96+chromium-110.0.5481.78)

Window resize,
The browser component does not update the layout until the adjustment is complete

![2023-04-07_22-45-19 (1)](https://user-images.githubusercontent.com/22113151/230628641-af51de4a-68b0-4628-8022-cbd5bbfc730b.gif)

**Comment by FriwiDev** [comment]
This is not an issue with jcefmaven, but with java-cef itself. Please report your issue here: https://github.com/chromiumembedded/java-cef instead.
