### ISSUE TITLE
Unable to find chrome_elf.dll program at the prompt in Win7

### ISSUE THREAD

**Issue by jackyHJ** [jcefmaven/jcefmaven#78]
**Describe the bug**
Unable to find chrome_elf.dll program at the prompt in Win7，Win10 can run normally

**To Reproduce**
1. CefApp.getInstance(args,settings)

**Expected behavior**

**Screenshots**
![图片](https://github.com/jcefmaven/jcefmaven/assets/32256773/b739dc8e-1a6c-4fdf-811f-c13f9cf7efc0)

**Environment (please complete the following information):**
 - OS: windows 7 sp1
 - Architecture: amd64
 - Version cef_binary_113.1.5+ge452d82+chromium-113.0.5672.93_windows64

**Additional context**

**Source code**
        CefSettings settings = new CefSettings();
        settings.windowless_rendering_enabled = useOSR;
        cefApp_ = CefApp.getInstance(args,settings);

**Comment by FriwiDev** [comment]
Please read the readme, this is not how you work with jcefmaven.

**Comment by jackyHJ** [comment]
Where is there a description in the readme,But I can run the same code in Win10，Can you give me some guidance？

**Comment by jackyHJ** [comment]
> Please read the readme, this is not how you work with jcefmaven.
Where is the relevant explanation in the readme,The same code can be run in Win10，Could you please give me some guidance？

**Comment by FriwiDev** [comment]
It is directly under "How to use", the long code block: https://github.com/jcefmaven/jcefmaven#how-to-use

You need to use the builder pattern to create your instance. You use the normal jcef approach which will not install the required dependencies for you. The browser needs to be downloaded and set up before you can actually use it. This is all automatic, but only if you use the builder.

**Comment by littleantsos** [comment]
@jackyHJ  hi,jackHJ,  I have also encountered the same problem. How did you solve.  can you  give me some suggestions

**Comment by lizhiwei8061** [comment]
Seeking help and solutions
