### ISSUE TITLE
Java-CEF v114 is available

### ISSUE THREAD

**Issue by jjlauer** [jcefmaven/jcefmaven#79]
Chrome v114 is now available for java-cef.  Was hoping this could be updated to the latest.

https://bitbucket.org/chromiumembedded/java-cef/commits/

**Comment by FriwiDev** [comment]
Yes, I am aware of that. Sadly the build for 114 is currently failing for jcefbuild, which this project depends on. I will leave this issue open and resolve it once I had the time to update to 114.

**Comment by FriwiDev** [comment]
Now we have v116.
