### ISSUE TITLE
 Java used fileDialog for swing Bug

### ISSUE THREAD

**Issue by hteste** [jcefmaven/jcefmaven#89]
**Error Info:
java.lang.UnsatisfiedLinkError: org.cef.callback.CefFileDialogCallback_N.N_Continue(JLjava/util/Vector;)V

I have tested all versions with this issue and have learned that only this method cannot be used
Addition:
N_Cancel method is Normal**

**Comment by hteste** [comment]
source view:
private final native void N_Continue(long self, Vector filePaths);

parameters error?

**Comment by FriwiDev** [comment]
I have no idea, but you should file this bug on the repository of jcef. It appears to be an issue concerning the sources. This project here only compiles and distributes jcef.
