### ISSUE TITLE
Upgrade to Chromium 119

### ISSUE THREAD

**Issue by zhelenskiy** [jcefmaven/jcefmaven#90]
**Is your feature request related to a problem? Please describe.**
Chromium 119 is already released and supported by CEF.
This version stabilizes Wasm-GC and introduces new instructions related to it.
That is why I would like to suggest updating JCEF to Chromium 119.

**Describe the solution you'd like**
Updated JCEF

**Describe alternatives you've considered**
None

**Additional context**
[Release of Wasm GC support in Chromium](https://chromestatus.com/feature/6062715726462976)
[Supported CEF versions](https://cef-builds.spotifycdn.com/index.html)

**Comment by FriwiDev** [comment]
This is just a repository providing builds for the most recent versions of jcef. If you wish to request a new version or help in updating, please visit the jcef repo and report it there: https://github.com/chromiumembedded/java-cef

**Comment by zhelenskiy** [comment]
Oops, sorry. I accidentally confused the repos.

**Comment by FriwiDev** [comment]
Its alright. Feel free to notify me once they update so I can run a new build :)

**Comment by zhelenskiy** [comment]
It seems they did it

**Comment by zhelenskiy** [comment]
https://github.com/jcefmaven/jcefbuild/releases

**Comment by zhelenskiy** [comment]
@FriwiDev Are there any updates?
