### ISSUE TITLE
NotAllowedError: Permission denied

### ISSUE THREAD

**Issue by xcmonline** [jcefmaven/jcefmaven#94]
use webRTC open video.

error: NotAllowedError: Permission denied

1、How to add the "enable-media-stream" parameter and set its value to 1
2、How to add the "enable-system-flash" parameter and set its value to 1
3、How to add the "enable-speech-input" parameter and set its value to 1

**Comment by FriwiDev** [comment]
Why is this marked as a bug? You can also add a question label if your problem concerns a question.

You can get a mutable list of arguments by using the getJCefArgs() method in the builder. You can then add your parameters to that list.

https://github.com/jcefmaven/jcefmaven/blob/master/jcefmaven/src/main/java/me/friwi/jcefmaven/CefAppBuilder.java#L111

**Comment by xcmonline** [comment]
thanks.
mark.

            builder.getJcefArgs().add("--enable-media-stream");
            builder.getJcefArgs().add("--enable-usermedia-screen-capturing");
            builder.getJcefArgs().add("--enable-system-flash");
            builder.getJcefArgs().add("--enable-speech-input");
