### ISSUE TITLE
The date input box is in English

### ISSUE THREAD

**Issue by lizhiwei8061** [jcefmaven/jcefmaven#97]
**Describe the bug**
The date input box is in English 
example p1

**To Reproduce**

**Expected behavior**
Other browsers are in Chinese
example p2

**Screenshots**
![image](https://github.com/jcefmaven/jcefmaven/assets/121220591/c609521f-870b-4106-97c8-557cce80db5f)
![image](https://github.com/jcefmaven/jcefmaven/assets/121220591/0bfa8495-e106-4846-ae47-70e0cc52f87e)

**Environment (please complete the following information):**
 - OS: windows
 - Architecture: amd64
 - Version: jcefmaven116.0.19.1

**Additional context**
May I ask if there is a solution

**Source code**
Add sources to reproduce the problem.

**Comment by FriwiDev** [comment]
Im by no means an expert, but I would assume that you need to set the browser locale from code in jcef. Have you tried this? You should be able to set it using a command line switch: https://magpcss.org/ceforum/viewtopic.php?f=6&t=15470
